# Generated by Django 5.0.1 on 2024-01-30 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0002_carlist_chassisnumber_carlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='chassisNumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
